In [21]:
# Importing all the Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [22]:
df = pd.read_csv('one_hot_encoded.csv')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293164 entries, 0 to 293163
Data columns (total 46 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             293164 non-null  int64
 1   distance               293164 non-null  float64
 2   avg_travel_time        293164 non-null  float64
 3   temp                   293164 non-null  float64
 4   clouds                 293164 non-null  float64
 5   pressure               293164 non-null  float64
 6   rain                   293164 non-null  float64
 7   humidity               293164 non-null  float64
 8   wind                   293164 non-null  float64
 9   Price                  293164 non-null  float64
 10  surge_multiplier_1.0   293164 non-null  int64
 11  surge_multiplier_1.25  293164 non-null  int64
 12  surge_multiplier_1.5   293164 non-null  int64
 13  surge_multiplier_1.75  293164 non-null  int64
 14  surge_multiplier_2.0   293164 non-null  int64
 15  surge_multiplier_2.5   293164 non-null  int64
 16  surge_multiplier_3.0   293164 non-null  int64
 17  cab_type_Lyft          293164 non-null  int64
 18  cab_type_Uber          293164 non-null  int64
 19  name_Black             293164 non-null  int64
 20  name_Black SUV         293164 non-null  int64
 21  name_Lux               293164 non-null  int64
 22  name_Lux Black         293164 non-null  int64
 23  name_Lux Black XL      293164 non-null  int64
 24  name_Lyft              293164 non-null  int64
 25  name_Lyft XL           293164 non-null  int64
 26  name_Shared            293164 non-null  int64
 27  name_UberPool          293164 non-null  int64
 28  name_UberX             293164 non-null  int64
 29  name_UberXL            293164 non-null  int64
 30  name_WAV               293164 non-null  int64
 31  day_0                  293164 non-null  int64
 32  day_1                  293164 non-null  int64
 33  day_2                  293164 non-null  int64
 34  day_3                  293164 non-null  int64
 35  day_4                  293164 non-null  int64
 36  day_5                  293164 non-null  int64
 37  day_6                  293164 non-null  int64
 38  class_hour_0           293164 non-null  int64
 39  class_hour_1           293164 non-null  int64
 40  class_hour_2           293164 non-null  int64
 41  class_hour_3           293164 non-null  int64
 42  class_hour_4           293164 non-null  int64
 43  class_hour_5           293164 non-null  int64
 44  class_hour_6           293164 non-null  int64
 45  class_hour_7           293164 non-null  int64
dtypes: float64(9), int64(37)
memory usage: 102.9 MB

In [24]:
df.columns

Index(['Unnamed: 0', 'distance', 'avg_travel_time', 'temp', 'clouds',
       'pressure', 'rain', 'humidity', 'wind', 'Price', 'surge_multiplier_1.0',
       'surge_multiplier_1.25', 'surge_multiplier_1.5',
       'surge_multiplier_1.75', 'surge_multiplier_2.0', 'surge_multiplier_2.5',
       'surge_multiplier_3.0', 'cab_type_Lyft', 'cab_type_Uber', 'name_Black',
       'name_Black SUV', 'name_Lux', 'name_Lux Black', 'name_Lux Black XL',
       'name_Lyft', 'name_Lyft XL', 'name_Shared', 'name_UberPool',
       'name_UberX', 'name_UberXL', 'name_WAV', 'day_0', 'day_1', 'day_2',
       'day_3', 'day_4', 'day_5', 'day_6', 'class_hour_0', 'class_hour_1',
       'class_hour_2', 'class_hour_3', 'class_hour_4', 'class_hour_5',
       'class_hour_6', 'class_hour_7'],
      dtype='object')

In [25]:
del df['Unnamed: 0']

In [26]:
df.columns

Index(['distance', 'avg_travel_time', 'temp', 'clouds', 'pressure', 'rain',
       'humidity', 'wind', 'Price', 'surge_multiplier_1.0',
       'surge_multiplier_1.25', 'surge_multiplier_1.5',
       'surge_multiplier_1.75', 'surge_multiplier_2.0', 'surge_multiplier_2.5',
       'surge_multiplier_3.0', 'cab_type_Lyft', 'cab_type_Uber', 'name_Black',
       'name_Black SUV', 'name_Lux', 'name_Lux Black', 'name_Lux Black XL',
       'name_Lyft', 'name_Lyft XL', 'name_Shared', 'name_UberPool',
       'name_UberX', 'name_UberXL', 'name_WAV', 'day_0', 'day_1', 'day_2',
       'day_3', 'day_4', 'day_5', 'day_6', 'class_hour_0', 'class_hour_1',
       'class_hour_2', 'class_hour_3', 'class_hour_4', 'class_hour_5',
       'class_hour_6', 'class_hour_7'],
      dtype='object')

In [27]:
df

,distance,avg_travel_time,temp,clouds,pressure,rain,humidity,wind,Price,surge_multiplier_1.0,...,day_5,day_6,class_hour_0,class_hour_1,class_hour_2,class_hour_3,class_hour_4,class_hour_5,class_hour_6,class_hour_7
0,-0.646748,-0.240554,-1.558765,-1.182438,0.099482,-0.21175,-2.237593,2.063766,5.300,1,...,0,0,0,0,0,0,0,1,0,0
1,1.748797,3.052229,-1.558765,-1.182438,0.099482,-0.21175,-2.237593,2.063766,14.310,1,...,0,0,0,0,0,0,0,1,0,0
2,0.374881,0.935440,-1.558765,-1.182438,0.099482,-0.21175,-2.237593,2.063766,8.400,1,...,0,0,0,0,0,0,0,1,0,0
3,0.198738,0.817840,-1.558765,-1.182438,0.099482,-0.21175,-2.237593,2.063766,17.325,1,...,0,0,0,0,0,0,0,1,0,0
4,-0.646748,-0.240554,-1.558765,-1.182438,0.099482,-0.21175,-2.237593,2.063766,5.300,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293159,0.101860,-1.534148,0.278701,0.642011,0.315441,-0.21175,1.334284,-1.496486,3.500,1,...,0,0,0,1,0,0,0,0,0,0
293160,0.101860,-1.534148,0.278701,0.642011,0.315441,-0.21175,1.334284,-1.496486,16.500,1,...,0,0,0,1,0,0,0,0,0,0
293161,0.004981,-0.240554,0.278701,0.642011,0.315441,-0.21175,1.334284,-1.496486,17.500,1,...,0,0,0,1,0,0,0,0,0,0
293162,0.004981,-0.240554,0.278701,0.642011,0.315441,-0.21175,1.334284,-1.496486,8.000,1,...,0,0,0,1,0,0,0,0,0,0
293163,0.004981,-0.240554,0.278701,0.642011,0.315441,-0.21175,1.334284,-1.496486,13.000,1,...,0,0,0,1,0,0,0,0,0,0

In [28]:
# storing the Dependent Variables in X and Independent Variable in Y
x=df.drop(['Price'],axis=1)
y=df['Price']

In [29]:
# Splitting the Data into Training set and Testing Set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((205214, 44), (87950, 44), (205214,), (87950,))

In [30]:
x_train.columns

Index(['distance', 'avg_travel_time', 'temp', 'clouds', 'pressure', 'rain',
       'humidity', 'wind', 'surge_multiplier_1.0', 'surge_multiplier_1.25',
       'surge_multiplier_1.5', 'surge_multiplier_1.75', 'surge_multiplier_2.0',
       'surge_multiplier_2.5', 'surge_multiplier_3.0', 'cab_type_Lyft',
       'cab_type_Uber', 'name_Black', 'name_Black SUV', 'name_Lux',
       'name_Lux Black', 'name_Lux Black XL', 'name_Lyft', 'name_Lyft XL',
       'name_Shared', 'name_UberPool', 'name_UberX', 'name_UberXL', 'name_WAV',
       'day_0', 'day_1', 'day_2', 'day_3', 'day_4', 'day_5', 'day_6',
       'class_hour_0', 'class_hour_1', 'class_hour_2', 'class_hour_3',
       'class_hour_4', 'class_hour_5', 'class_hour_6', 'class_hour_7'],
      dtype='object')

In [31]:
a={'Model Name':[], 'Mean_Absolute_Error_MAE':[] ,'Adj_R_Square':[] ,'Root_Mean_Squared_Error_RMSE':[] ,'Mean_Absolute_Percentage_Error_MAPE':[] ,'Mean_Squared_Error_MSE':[] ,'Root_Mean_Squared_Log_Error_RMSLE':[] ,'R2_score':[]}
Results=pd.DataFrame(a)
Results.head()

Empty DataFrame
Columns: [Model Name, Mean_Absolute_Error_MAE, Adj_R_Square, Root_Mean_Squared_Error_RMSE, Mean_Absolute_Percentage_Error_MAPE, Mean_Squared_Error_MSE, Root_Mean_Squared_Log_Error_RMSLE, R2_score]
Index: []

In [32]:
# create the dist and  then dataframe
result_dict = list()

In [ ]:
# Build the Regression / Regressor models

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn import linear_model
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
import xgboost as xgb
from sklearn.ensemble import GradientBoostingRegressor

# Create objects of Regression / Regressor models with default hyper-parameters

modelmlg = LinearRegression()
modeldcr = DecisionTreeRegressor()
modelrfr = RandomForestRegressor()
modelSVR = SVR()
modelXGR = xgb.XGBRegressor()
modelRE=Ridge()
modelLO=linear_model.Lasso(alpha=0.1)

modelGBR = GradientBoostingRegressor(loss='ls', learning_rate=0.1, n_estimators=100, subsample=1.0,
                                     criterion='friedman_mse', min_samples_split=2, min_samples_leaf=1,
                                     min_weight_fraction_leaf=0.0, max_depth=3, min_impurity_decrease=0.0,
                                     init=None, random_state=None, max_features=None,
                                     alpha=0.9, verbose=0, max_leaf_nodes=None, warm_start=False,
                                     validation_fraction=0.1, n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0)

# Evalution matrix for all the algorithms

MM = [modelmlg, modeldcr, modelrfr,modelXGR,modelSVR,modelRE,modelLO,modelGBR]


for models in MM:
    
    # Fit the model with train data
    
    models.fit(x_train, y_train)
    
    # Predict the model with test data

    y_pred = models.predict(x_test)
    
    # Print the model name
    
    print('Model Name: ', models)
    
    # Evaluation metrics for Regression analysis

    from sklearn import metrics

    print('Mean Absolute Error (MAE):', round(metrics.mean_absolute_error(y_test, y_pred),3))  
    print('Mean Squared Error (MSE):', round(metrics.mean_squared_error(y_test, y_pred),3))  
    print('Root Mean Squared Error (RMSE):', round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))
    print('R2_score:', round(metrics.r2_score(y_test, y_pred),6))
    print('Root Mean Squared Log Error (RMSLE):', round(np.log(np.sqrt(metrics.mean_squared_error(y_test, y_pred))),3))
    
    # Define the function to calculate the MAPE - Mean Absolute Percentage Error

    def MAPE (y_test, y_pred):
        y_test, y_pred = np.array(y_test), np.array(y_pred)
        return np.mean(np.abs((y_test - y_pred) / y_test)) * 100
    
    # Evaluation of MAPE 

    result = MAPE(y_test, y_pred)
    print('Mean Absolute Percentage Error (MAPE):', round(result, 2), '%')
    
    # Calculate Adjusted R squared values 

    r_squared = round(metrics.r2_score(y_test, y_pred),6)
    adjusted_r_squared = round(1 - (1-r_squared)*(len(y)-1)/(len(y)-x.shape[1]-1),6)
    print('Adj R Square: ', adjusted_r_squared)
    print('------------------------------------------------------------------------------------------------------------')
    #-------------------------------------------------------------------------------------------
    new_row = {'Model Name' : models,
               'Mean_Absolute_Error_MAE' : metrics.mean_absolute_error(y_test, y_pred),
               'Adj_R_Square' : adjusted_r_squared,
               'Root_Mean_Squared_Error_RMSE' : np.sqrt(metrics.mean_squared_error(y_test, y_pred)),
               'Mean_Absolute_Percentage_Error_MAPE' : result,
               'Mean_Squared_Error_MSE' : metrics.mean_squared_error(y_test, y_pred),
               'Root_Mean_Squared_Log_Error_RMSLE': np.log(np.sqrt(metrics.mean_squared_error(y_test, y_pred))),
               'R2_score' : metrics.r2_score(y_test, y_pred)}
    result_dict.append(new_row)

Model Name:  LinearRegression()
Mean Absolute Error (MAE): 1.97
Mean Squared Error (MSE): 7.727
Root Mean Squared Error (RMSE): 2.78
R2_score: 0.92454
Root Mean Squared Log Error (RMSLE): 1.022
Mean Absolute Percentage Error (MAPE): 14.13 %
Adj R Square:  0.924529
------------------------------------------------------------------------------------------------------------
Model Name:  DecisionTreeRegressor()
Mean Absolute Error (MAE): 1.257
Mean Squared Error (MSE): 5.298
Root Mean Squared Error (RMSE): 2.302
R2_score: 0.948258
Root Mean Squared Log Error (RMSLE): 0.834
Mean Absolute Percentage Error (MAPE): 8.57 %
Adj R Square:  0.94825
------------------------------------------------------------------------------------------------------------
Model Name:  RandomForestRegressor()
Mean Absolute Error (MAE): 1.106
Mean Squared Error (MSE): 3.312
Root Mean Squared Error (RMSE): 1.82
R2_score: 0.967657
Root Mean Squared Log Error (RMSLE): 0.599
Mean Absolute Percentage Error (MAPE): 7.58 %
Adj R Square:  0.967652
------------------------------------------------------------------------------------------------------------
Model Name:  XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)
Mean Absolute Error (MAE): 1.236
Mean Squared Error (MSE): 3.519
Root Mean Squared Error (RMSE): 1.876
R2_score: 0.965633
Root Mean Squared Log Error (RMSLE): 0.629
Mean Absolute Percentage Error (MAPE): 8.53 %
Adj R Square:  0.965628
------------------------------------------------------------------------------------------------------------

In [41]:
Results = pd.DataFrame(result_dict)

In [42]:
Results

,Model Name,Mean_Absolute_Error_MAE,Adj_R_Square,Root_Mean_Squared_Error_RMSE,Mean_Absolute_Percentage_Error_MAPE,Mean_Squared_Error_MSE,Root_Mean_Squared_Log_Error_RMSLE,R2_score
0,LinearRegression(),1.969510,0.924529,2.779760,14.126825,7.727064,1.022365,0.924540
1,DecisionTreeRegressor(),1.259524,0.947594,2.316363,8.586943,5.365539,0.839998,0.947602
2,"(DecisionTreeRegressor(max_features=1.0, rando...",1.106549,0.967641,1.820179,7.587303,3.313050,0.598935,0.967646
3,"XGBRegressor(base_score=None, booster=None, ca...",1.235563,0.965628,1.875930,8.528026,3.519115,0.629105,0.965633
4,(DecisionTreeRegressor(random_state=876528922)...,1.147494,0.965259,1.885983,7.872993,3.556930,0.634449,0.965264
5,SVR(),1.370352,0.951599,2.226098,9.070631,4.955511,0.800250,0.951606
6,Ridge(),1.969297,0.924537,2.779608,14.127207,7.726220,1.022310,0.924548
7,Lasso(alpha=0.1),2.163892,0.895975,3.263501,14.737732,10.650442,1.182801,0.895991

In [ ]:
import pickle
with open("pickel_model_file_linear_regression.pkl", "wb") as f:
    pickle.dump(modelmlg,f)

In [44]:

with open("pickel_model_file_rfr.pkl", "wb") as f:
    pickle.dump(modelrfr,f)